version: '3.8'

services:
  # 1. BASE DE DATOS (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: uce_trade_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: uce_trade_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. CACHÃ‰ (Redis - Requisito del Inge)
  redis:
    image: redis:alpine
    container_name: uce_trade_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: